### ISSUE TITLE
Error: Illegal argument: character must be non-negative

### ISSUE THREAD

**Issue by kwonoj** [Durzn/BracketHighlighter#5]
```
at translate (c:\Users\oooo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:361:876)
	at getStartSymbolFromSelection (c:\Users\oooo\.vscode\extensions\durzn.brackethighlighter-1.4.1\out\extension.js:183:73)
	at handleTextSelectionEvent (c:\Users\oooo\.vscode\extensions\durzn.brackethighlighter-1.4.1\out\extension.js:68:23
```

https://github.com/Durzn/BracketHighlighter/blob/master/src/extension.ts#L169
https://github.com/Durzn/BracketHighlighter/blob/master/src/extension.ts#L191

(and potentially some other places) can throw when position has `character` with `0`.

**Comment by Durzn** [comment]
Thank you. Fixed the crash with commit 853b056.
